### PR TITLE
Fixed broken image asset manager

### PR DESCRIPTION
**Pull request by pmill**
This commit fixes the broken asset manager from issue #6

### CODE REVIEW

**Comment by Uysim** [comment]
I wish to see this merge

**Comment by kaoz70** [comment]
Hello, I'm the new maintainer of this repo, could you please update to the latest changes and resolve all conflicts so that I can merge this?

**Comment by pmill** [comment]
Updated

**Comment by pmill** [comment]
I don't think this fix is included in the latest npm version, at least when I `npm install grapesjs-blocks-bootstrap4@latest` I can't see these changes in the files installed into `node_modules`.

**Comment by kaoz70** [comment]
I seems I forgot to publish the new build to NPM, can you check if you get the new version 0.1.15 now?

**Pull request merged**
